public class queueMain{
public static void main(String args[]){
        System.out.println("Queue witrh circular array");
    CircularQueue_arr<Integer> queue=new CircularQueue_arr<>(10);
    queue.enqueue(12);
    queue.enqueue(8);
      queue.enqueue(17);
    queue.enqueue(80);
      queue.enqueue(13);
    queue.enqueue(42);
      queue.enqueue(33);
    queue.enqueue(49);
    queue.printAll();
    System.out.println();
    System.out.println("Size of queue: "+ queue.getSize());
    System.out.println("Dequeued: "+ queue.dequeue());
     System.out.println("Dequeued: "+ queue.dequeue());
      queue.printAll();
    System.out.println();
       System.out.println("Peeked: "+ queue.peek());
    System.out.println("Size of queue: "+ queue.getSize());
        System.out.println();
System.out.println("Queue with Linked list");
LinkedList_Queue<Integer> queueLL= new LinkedList_Queue<>();
 queueLL.enqueue(12);
    queueLL.enqueue(8);
      queueLL.enqueue(17);
    queueLL.enqueue(80);
      queueLL.enqueue(13);
    queueLL.enqueue(42);
      queueLL.enqueue(33);
    queueLL.enqueue(49);
     queueLL.printAll();
    System.out.println();
    System.out.println("Size of queue: "+ queueLL.getSize());
    System.out.println("Dequeued: "+ queueLL.dequeue());
     System.out.println("Dequeued: "+ queueLL.dequeue());
      queueLL.printAll();
    System.out.println();
       System.out.println("Peeked: "+ queueLL.peek());
    System.out.println("Size of queue: "+ queueLL.getSize());
    System.out.println();
    System.out.println("Queue with double stacks");
TwoStacks_Queue<Integer> queueStk= new TwoStacks_Queue<>();
 queueStk.enqueue(12);
    queueStk.enqueue(8);
      queueStk.enqueue(17);
    queueStk.enqueue(80);
      queueStk.enqueue(13);
    queueStk.enqueue(42);
      queueStk.enqueue(33);
    queueStk.enqueue(49);
     queueStk.printAll();
    System.out.println();
    System.out.println("Size of queue: "+ queueStk.getSize());
    System.out.println("Dequeued: "+ queueStk.dequeue());
     System.out.println("Dequeued: "+ queueStk.dequeue());
      queueStk.printAll();
    System.out.println();
        System.out.println("Peeked: "+ queueStk.peekfromFront());
    System.out.println("Size of queue: "+ queueStk.getSize());
}
}